name: GitHub Metrics - Complete Pack

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:

  overview:
    name: Overview
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Josue-Augusto
          filename: metrics-overview.svg
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: America/Sao_Paulo

  languages:
    name: Languages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Josue-Augusto
          filename: metrics-languages.svg
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8

  habits:
    name: Coding Habits
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Josue-Augusto
          filename: metrics-habits.svg
          template: classic
          base: ""
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes

  isocalendar:
    name: Contribution Calendar
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Josue-Augusto
          filename: metrics-isocalendar.svg
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  stars:
    name: Stars & Stargazers
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Josue-Augusto
          filename: metrics-stars.svg
          template: classic
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts: yes

  followers:
    name: Followers Graph
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Josue-Augusto
          filename: metrics-followers.svg
          template: classic
          base: ""
          plugin_followup: yes

  repositories:
    name: Repositories Summary
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Josue-Augusto
          filename: metrics-repositories.svg
          template: classic
          base: repositories
          plugin_repositories: yes
          plugin_repositories_pinned: yes

  achievements:
    name: Achievements
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Josue-Augusto
          filename: metrics-achievements.svg
          template: classic
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact

  activity:
    name: Commit Activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Josue-Augusto
          filename: metrics-activity.svg
          template: classic
          base: activity

  discussions:
    name: Discussions / Community
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Josue-Augusto
          filename: metrics-discussions.svg
          template: classic
          base: ""
          plugin_discussions: yes
