name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: Josue-Augusto
          template: classic
          config_timezone: America/Sao_Paulo

          # Ativar repositórios privados
          base: header, activity, community, repositories, metadata
          repositories_affiliations: owner, collaborator, organization_member

          # Ativar commits privados
          plugin_activity: yes
          plugin_activity_visibility: public, private

          # Linguagens (incluindo privadas)
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_indepth: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 12
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_categories: data, programming

          # Projetos (privados inclusos)
          plugin_projects: yes
          plugin_projects_repos: 100
          plugin_projects_descriptions: yes

          # Commits timeline
          plugin_followup: yes
          plugin_followup_sections: user

          # Estatísticas gerais
          plugin_lines: yes

          # Horários de atividade
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          # Commits por horário
          plugin_calendar: yes
          plugin_calendar_limit: 1

          # Repos em destaque
          plugin_repositories: yes
          plugin_repositories_featured: 0
