name: GitHub Metrics

on:
  schedule: 
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Josue-Augusto
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: America/Sao_Paulo

          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_stargazers: yes
          plugin_stargazers_charts: yes

          plugin_followup: yes
          plugin_followup_indepth: yes

          plugin_repositories: yes
          plugin_repositories_pinned: yes

          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
