name: GitHub Metrics - Split

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:

  overview:
    name: Overview
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Josue-Augusto
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: America/Sao_Paulo
          filename: metrics-overview.svg

  languages:
    name: Languages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Josue-Augusto
          filename: metrics-languages.svg
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8

  habits:
    name: Coding Habits
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Josue-Augusto
          filename: metrics-habits.svg
          template: classic
          base: ""
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes

  stargazers:
    name: Stargazers
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Josue-Augusto
          filename: metrics-stars.svg
          template: classic
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
